spring.application.name=vocab
server.forward-headers-strategy=framework

# -----------------------------
# Database (PostgreSQL)
# -----------------------------
# URL of local database
spring.datasource.url=jdbc:postgresql://localhost:5432/vocabdb
# DB username and password used by Spring Boot
spring.datasource.username=vocabuser
spring.datasource.password=vocabpass


# JPA / Hibernate
# update = keep existing tables and add missing columns automatically
spring.jpa.hibernate.ddl-auto=update
# Show SQL in console 
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

# SQL dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=versesadi@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# false = app can start even if SMTP is temporarily unavailable
spring.mail.test-connection=false

app.mail.log-links=true
