spring.application.name=vocab
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/vocabdb
spring.datasource.username=vocabuser
spring.datasource.password=vocabpass

# JPA settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Optional (good for debugging)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect